import type { CartonLine } from "@/domain/types";

/** Jeu de données de démonstration, chargeable en un clic pour tester l'application immédiatement. */
export const DEMO_CARTON_LINES: CartonLine[] = [
  {
    sku: "ELEC-CARTON-A",
    dimensions: { length: 400, width: 300, height: 250 },
    quantity: 24,
    weightKg: 8.5,
    allowRotation: true,
    uprightOnly: false,
    fragile: false,
    stackable: true,
    productGroup: "electromenager",
  },
  {
    sku: "ELEC-CARTON-B",
    dimensions: { length: 600, width: 400, height: 300 },
    quantity: 12,
    weightKg: 14,
    allowRotation: true,
    uprightOnly: true,
    fragile: false,
    stackable: true,
    productGroup: "electromenager",
  },
  {
    sku: "VERRE-FRAGILE",
    dimensions: { length: 300, width: 250, height: 200 },
    quantity: 18,
    weightKg: 4,
    allowRotation: true,
    uprightOnly: true,
    fragile: true,
    stackable: true,
    maxSupportedWeightKg: 2,
    productGroup: "verrerie",
    incompatibleGroups: ["chimie"],
  },
  {
    sku: "PALETTE-SOCLE",
    dimensions: { length: 1200, width: 800, height: 150 },
    quantity: 2,
    weightKg: 60,
    allowRotation: false,
    uprightOnly: true,
    fragile: false,
    stackable: false,
    productGroup: "socle",
  },
  {
    sku: "PIECES-DETACHEES",
    dimensions: { length: 250, width: 200, height: 150 },
    quantity: 40,
    weightKg: 3,
    allowRotation: true,
    uprightOnly: false,
    fragile: false,
    stackable: true,
    productGroup: "pieces",
  },
  {
    sku: "BIDONS-CHIMIE",
    dimensions: { length: 350, width: 350, height: 400 },
    quantity: 10,
    weightKg: 18,
    allowRotation: false,
    uprightOnly: true,
    fragile: false,
    stackable: true,
    productGroup: "chimie",
  },
  {
    sku: "HORS-GABARIT",
    dimensions: { length: 1400, width: 900, height: 500 },
    quantity: 1,
    weightKg: 45,
    allowRotation: true,
    uprightOnly: false,
    fragile: false,
    stackable: false,
  },
];

export const DEMO_SIMULATION_NAME = "Démonstration — commande mixte";
